//! End-to-end CLI tests: run the built `nose` binary against a temp project and
//! check the user-visible behavior (discovery, `scan` report, `--exclude`).

pub(crate) use std::fs;
pub(crate) use std::path::{Path, PathBuf};
pub(crate) use std::process::{Command, Stdio};

pub(crate) fn bin() -> &'static str {
    env!("CARGO_BIN_EXE_nose")
}

/// Write a small project (a 3-copy clone family + a decoy) into a unique temp dir.
pub(crate) fn make_project(tag: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("nose_cli_{tag}_{}", std::process::id()));
    let _ = fs::remove_dir_all(&dir);
    let body = |acc: &str, it: &str| {
        format!("def f(items):\n    {acc} = 0\n    for {it} in items:\n        if {it} > 0:\n            {acc} = {acc} + {it} * {it}\n    return {acc}\n")
    };
    for (sub, src) in [
        ("a", body("total", "x")),
        ("b", body("acc", "v")),
        ("tests", body("s", "n")),
    ] {
        let d = dir.join(sub);
        fs::create_dir_all(&d).unwrap();
        fs::write(d.join("f.py"), src).unwrap();
    }
    let d = dir.join("c");
    fs::create_dir_all(&d).unwrap();
    fs::write(
        d.join("decoy.py"),
        "def greet(n):\n    m = 'hi ' + n\n    print(m)\n    print(n)\n    return m\n",
    )
    .unwrap();
    dir
}

pub(crate) fn make_mode_project(tag: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("nose_modes_{tag}_{}", std::process::id()));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).unwrap();

    fs::write(
        dir.join("renamed_a.py"),
        "def total(items):\n    total = 0\n    for item in items:\n        if item > 0:\n            total = total + item * item\n    return total\n",
    )
    .unwrap();
    fs::write(
        dir.join("renamed_b.py"),
        "def score(values):\n    acc = 0\n    for value in values:\n        if value > 0:\n            acc = acc + value * value\n    return acc\n",
    )
    .unwrap();

    let copied = "def copied(events):\n    out = []\n    for e in events:\n        if e.kind == 1:\n            out.append(e.payload)\n            record(e.id, e.kind)\n    return out\n";
    fs::write(dir.join("copy_a.py"), copied).unwrap();
    fs::write(dir.join("copy_b.py"), copied).unwrap();

    // A near-duplicate pair: mostly the same body, but each side has one
    // statement the other lacks — different raw tokens (no syntax run),
    // different value fingerprints (no exact semantic), near-similar shape.
    fs::write(
        dir.join("near_a.py"),
        "def fetch_users(client, ids):\n    results = []\n    for uid in ids:\n        row = client.get(uid)\n        if row is None:\n            continue\n        results.append(normalize(row))\n    log_count(len(results))\n    return results\n",
    )
    .unwrap();
    fs::write(
        dir.join("near_b.py"),
        "def fetch_orders(client, keys):\n    found = []\n    for key in keys:\n        record = client.get(key)\n        if record is None:\n            continue\n        found.append(normalize(record))\n        audit(record)\n    return found\n",
    )
    .unwrap();

    dir
}

pub(crate) fn make_fragment_project(tag: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("nose_frag_{tag}_{}", std::process::id()));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(dir.join("a")).unwrap();
    fs::create_dir_all(dir.join("b")).unwrap();
    fs::write(
        dir.join("a/f.py"),
        "def first(xs):\n    total = 0\n    if xs:\n        return xs[0] + 1\n    return total\n",
    )
    .unwrap();
    fs::write(
        dir.join("b/f.py"),
        "def second(items):\n    acc = 10\n    if items:\n        return items[0] + 1\n    return acc\n",
    )
    .unwrap();
    dir
}

pub(crate) fn make_generated_header_project(tag: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("nose_genhdr_{tag}_{}", std::process::id()));
    let _ = fs::remove_dir_all(&dir);
    let body = |name: &str, acc: &str, it: &str| {
        format!(
            "# Generated by fixture\n\
def {name}(items):\n    {acc} = 0\n    for {it} in items:\n        if {it} > 0:\n            {acc} = {acc} + {it} * {it}\n    return {acc}\n"
        )
    };
    for (sub, src) in [
        ("a", body("first", "total", "x")),
        ("b", body("second", "acc", "v")),
        ("c", body("third", "sum", "n")),
    ] {
        let d = dir.join(sub);
        fs::create_dir_all(&d).unwrap();
        fs::write(d.join("f.py"), src).unwrap();
    }
    dir
}

pub(crate) fn run(args: &[&str]) -> String {
    let out = Command::new(bin()).args(args).output().expect("run nose");
    assert!(
        out.status.success(),
        "nose exited non-zero: {:?}",
        out.status
    );
    String::from_utf8(out.stdout).unwrap()
}

/// Like [`run`] but expects a non-zero exit; returns stderr (where errors print).
#[allow(dead_code)]
pub(crate) fn run_fail(args: &[&str]) -> String {
    let out = Command::new(bin()).args(args).output().expect("run nose");
    assert!(
        !out.status.success(),
        "expected nose to fail, but it succeeded"
    );
    String::from_utf8(out.stderr).unwrap()
}

/// `nose scan <dir> --mode <mode> --format json --top 0` with the tiny-fixture
/// floors (`--min-lines 1 --min-size 1`) — the standard invocation for the
/// one-function fixtures the semantic CLI tests are built from.
pub(crate) fn scan_min_json(dir: &Path, mode: &str) -> String {
    run(&[
        "scan",
        dir.to_str().unwrap(),
        "--mode",
        mode,
        "--min-lines",
        "1",
        "--min-size",
        "1",
        "--format",
        "json",
        "--top",
        "0",
    ])
}

pub(crate) fn add_distinct_clone_family(dir: &Path) {
    let d = dir.join("new");
    fs::create_dir_all(&d).unwrap();
    let body = |name: &str, acc: &str, it: &str| {
        format!(
            "def {name}(items):\n    {acc} = 1\n    for {it} in items:\n        if {it} < 10:\n            {acc} = {acc} * ({it} + 3)\n            {acc} = {acc} - {it}\n    return {acc}\n"
        )
    };
    fs::write(d.join("fresh_a.py"), body("fresh_a", "total", "item")).unwrap();
    fs::write(d.join("fresh_b.py"), body("fresh_b", "score", "value")).unwrap();
}

pub(crate) fn add_member_to_existing_family(dir: &Path) {
    let d = dir.join("d");
    fs::create_dir_all(&d).unwrap();
    fs::write(
        d.join("f.py"),
        "def f(items):\n    sum = 0\n    for z in items:\n        if z > 0:\n            sum = sum + z * z\n    return sum\n",
    )
    .unwrap();
}

pub(crate) fn scan_json(out: &str) -> serde_json::Value {
    serde_json::from_str(out).expect("scan should emit valid JSON")
}

pub(crate) fn scan_families(json: &serde_json::Value) -> &[serde_json::Value] {
    json["families"]
        .as_array()
        .expect("scan JSON should contain families array")
}

pub(crate) fn family_contains_all(json: &serde_json::Value, suffixes: &[&str]) -> bool {
    family_with_all(json, suffixes).is_some()
}

pub(crate) fn family_with_all<'a>(
    json: &'a serde_json::Value,
    suffixes: &[&str],
) -> Option<&'a serde_json::Value> {
    scan_families(json).iter().find(|family| {
        let Some(locations) = family["locations"].as_array() else {
            return false;
        };
        suffixes.iter().all(|suffix| {
            locations.iter().any(|loc| {
                loc["file"]
                    .as_str()
                    .is_some_and(|file| file.ends_with(suffix))
            })
        })
    })
}

/// Find a family that pairs `left` and `right` as locations at exactly
/// `start_line..end_line`, where every location is a `Block` and none sits in
/// `negative` — the standard positive check for branch-boundary fragment tests.
pub(crate) fn block_branch_pair_family<'a>(
    families: &'a [serde_json::Value],
    left: &str,
    right: &str,
    negative: &str,
    start_line: u64,
    end_line: u64,
) -> Option<&'a serde_json::Value> {
    families.iter().find(|family| {
        let locations = family["locations"].as_array().expect("locations");
        let branch_files: Vec<&str> = locations
            .iter()
            .filter(|loc| loc["start_line"] == start_line && loc["end_line"] == end_line)
            .filter_map(|loc| loc["file"].as_str())
            .collect();
        branch_files.iter().any(|file| file.ends_with(left))
            && branch_files.iter().any(|file| file.ends_with(right))
            && locations.iter().all(|loc| loc["kind"] == "Block")
            && locations
                .iter()
                .filter_map(|loc| loc["file"].as_str())
                .all(|file| !file.ends_with(negative))
    })
}

/// Whether any family pairs `left` at `(start, end)` with `right` at its
/// `(start, end)` — the standard negative check for branch-boundary tests
/// (asserting two spans were NOT merged into one family).
pub(crate) fn families_pair_locations(
    families: &[serde_json::Value],
    left: (&str, u64, u64),
    right: (&str, u64, u64),
) -> bool {
    fn has_location(locations: &[serde_json::Value], (file, start, end): (&str, u64, u64)) -> bool {
        locations.iter().any(|loc| {
            loc["file"].as_str().is_some_and(|f| f.ends_with(file))
                && loc["start_line"] == start
                && loc["end_line"] == end
        })
    }
    families.iter().any(|family| {
        let locations = family["locations"].as_array().expect("locations");
        has_location(locations, left) && has_location(locations, right)
    })
}

pub(crate) fn json_array_strings<'a>(value: &'a serde_json::Value, key: &str) -> Vec<&'a str> {
    value[key]
        .as_array()
        .unwrap_or_else(|| panic!("{key} should be an array"))
        .iter()
        .map(|item| {
            item.as_str()
                .unwrap_or_else(|| panic!("{key} entries should be strings"))
        })
        .collect()
}

pub(crate) fn assert_scan_json_v1_contract(json: &serde_json::Value) {
    assert_eq!(json["schema_version"], 1);
    assert!(
        json["tool_version"].as_str().is_some_and(|s| !s.is_empty()),
        "tool_version should be a non-empty string: {json}"
    );
    assert!(
        json["scope"]["files"].is_number(),
        "scope.files should be numeric: {json}"
    );
    assert!(
        json["scope"]["languages"].as_array().is_some(),
        "scope.languages should be an array: {json}"
    );
    let packs = json["semantic_packs"]
        .as_array()
        .expect("semantic_packs should be an array");
    let first_party = packs
        .first()
        .and_then(|pack| pack.as_object())
        .expect("semantic_packs should include first-party provenance");
    for key in [
        "id",
        "hash",
        "kind",
        "version",
        "display_name",
        "trust",
        "enabled_by_default",
        "source",
        "influence",
        "provider",
        "repository",
        "license",
        "supported_languages",
        "counts",
    ] {
        assert!(
            first_party.contains_key(key),
            "semantic_packs[0].{key} missing: {json}"
        );
    }

    let ranking = json["ranking"].as_object().expect("ranking object");
    for key in [
        "sort",
        "total_families",
        "shown_families",
        "limit",
        "surface_counts",
    ] {
        assert!(ranking.contains_key(key), "ranking.{key} missing: {json}");
    }
    assert_scan_json_surface_counts_contract(json, ranking);

    let family = scan_families(json)
        .first()
        .expect("fixture should include a family");
    assert_scan_json_family_ids_unique(json);
    let family = family.as_object().expect("family object");
    for key in [
        "family_id",
        "value",
        "members",
        "files",
        "modules",
        "languages",
        "mean_score",
        "mean_lines",
        "dup_lines",
        "shared_lines",
        "params",
        "shared_weight",
        "locations",
        "mean_sem",
        "scope",
        "discount",
        "recommended_surface",
    ] {
        assert!(family.contains_key(key), "family.{key} missing: {json}");
    }

    let loc = family["locations"]
        .as_array()
        .and_then(|locations| locations.first())
        .and_then(|location| location.as_object())
        .expect("family.locations should contain location objects");
    for key in [
        "file",
        "start_line",
        "end_line",
        "lang",
        "kind",
        "sem",
        "span_lines",
        "span_tokens",
        "is_fragment",
    ] {
        assert!(loc.contains_key(key), "location.{key} missing: {json}");
    }
}

fn assert_scan_json_family_ids_unique(json: &serde_json::Value) {
    let mut family_ids = std::collections::BTreeSet::new();
    for family in scan_families(json) {
        let id = family["family_id"]
            .as_str()
            .unwrap_or_else(|| panic!("family.family_id should be a string: {json}"));
        assert!(
            family_ids.insert(id),
            "family_id values must be unique within families[]: {json}"
        );
    }
}

fn assert_scan_json_surface_counts_contract(
    json: &serde_json::Value,
    ranking: &serde_json::Map<String, serde_json::Value>,
) {
    let surface_counts = ranking["surface_counts"]
        .as_object()
        .expect("ranking.surface_counts object");
    for key in [
        "default",
        "review",
        "hidden",
        "debug",
        "generated",
        "declaration",
        "shallow",
        "fragments",
    ] {
        assert!(
            surface_counts.contains_key(key),
            "ranking.surface_counts.{key} missing: {json}"
        );
    }
    let fragment_counts = surface_counts["fragments"]
        .as_object()
        .expect("ranking.surface_counts.fragments object");
    for key in ["total", "default", "review", "hidden", "debug"] {
        assert!(
            fragment_counts.contains_key(key),
            "ranking.surface_counts.fragments.{key} missing: {json}"
        );
    }
}
