//! End-to-end CLI tests: run the built `nose` binary against a temp project and
//! check the user-visible behavior (discovery, `scan` report, `--exclude`).

pub(crate) use std::fs;
pub(crate) use std::path::{Path, PathBuf};
pub(crate) use std::process::{Command, Stdio};

pub(crate) fn bin() -> &'static str {
    env!("CARGO_BIN_EXE_nose")
}

/// Write a small project (a 3-copy clone family + a decoy) into a unique temp dir.
pub(crate) fn make_project(tag: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("nose_cli_{tag}_{}", std::process::id()));
    let _ = fs::remove_dir_all(&dir);
    let body = |acc: &str, it: &str| {
        format!("def f(items):\n    {acc} = 0\n    for {it} in items:\n        if {it} > 0:\n            {acc} = {acc} + {it} * {it}\n    return {acc}\n")
    };
    for (sub, src) in [
        ("a", body("total", "x")),
        ("b", body("acc", "v")),
        ("tests", body("s", "n")),
    ] {
        let d = dir.join(sub);
        fs::create_dir_all(&d).unwrap();
        fs::write(d.join("f.py"), src).unwrap();
    }
    let d = dir.join("c");
    fs::create_dir_all(&d).unwrap();
    fs::write(
        d.join("decoy.py"),
        "def greet(n):\n    m = 'hi ' + n\n    print(m)\n    print(n)\n    return m\n",
    )
    .unwrap();
    dir
}

pub(crate) fn make_mode_project(tag: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("nose_modes_{tag}_{}", std::process::id()));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).unwrap();

    fs::write(
        dir.join("renamed_a.py"),
        "def total(items):\n    total = 0\n    for item in items:\n        if item > 0:\n            total = total + item * item\n    return total\n",
    )
    .unwrap();
    fs::write(
        dir.join("renamed_b.py"),
        "def score(values):\n    acc = 0\n    for value in values:\n        if value > 0:\n            acc = acc + value * value\n    return acc\n",
    )
    .unwrap();

    let copied = "def copied(events):\n    out = []\n    for e in events:\n        if e.kind == 1:\n            out.append(e.payload)\n            record(e.id, e.kind)\n    return out\n";
    fs::write(dir.join("copy_a.py"), copied).unwrap();
    fs::write(dir.join("copy_b.py"), copied).unwrap();

    dir
}

pub(crate) fn make_fragment_project(tag: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("nose_frag_{tag}_{}", std::process::id()));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(dir.join("a")).unwrap();
    fs::create_dir_all(dir.join("b")).unwrap();
    fs::write(
        dir.join("a/f.py"),
        "def first(xs):\n    total = 0\n    if xs:\n        return xs[0] + 1\n    return total\n",
    )
    .unwrap();
    fs::write(
        dir.join("b/f.py"),
        "def second(items):\n    acc = 10\n    if items:\n        return items[0] + 1\n    return acc\n",
    )
    .unwrap();
    dir
}

pub(crate) fn make_generated_header_project(tag: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("nose_genhdr_{tag}_{}", std::process::id()));
    let _ = fs::remove_dir_all(&dir);
    let body = |name: &str, acc: &str, it: &str| {
        format!(
            "# Generated by fixture\n\
def {name}(items):\n    {acc} = 0\n    for {it} in items:\n        if {it} > 0:\n            {acc} = {acc} + {it} * {it}\n    return {acc}\n"
        )
    };
    for (sub, src) in [
        ("a", body("first", "total", "x")),
        ("b", body("second", "acc", "v")),
        ("c", body("third", "sum", "n")),
    ] {
        let d = dir.join(sub);
        fs::create_dir_all(&d).unwrap();
        fs::write(d.join("f.py"), src).unwrap();
    }
    dir
}

pub(crate) fn run(args: &[&str]) -> String {
    let out = Command::new(bin()).args(args).output().expect("run nose");
    assert!(
        out.status.success(),
        "nose exited non-zero: {:?}",
        out.status
    );
    String::from_utf8(out.stdout).unwrap()
}

pub(crate) fn add_distinct_clone_family(dir: &Path) {
    let d = dir.join("new");
    fs::create_dir_all(&d).unwrap();
    let body = |name: &str, acc: &str, it: &str| {
        format!(
            "def {name}(items):\n    {acc} = 1\n    for {it} in items:\n        if {it} < 10:\n            {acc} = {acc} * ({it} + 3)\n            {acc} = {acc} - {it}\n    return {acc}\n"
        )
    };
    fs::write(d.join("fresh_a.py"), body("fresh_a", "total", "item")).unwrap();
    fs::write(d.join("fresh_b.py"), body("fresh_b", "score", "value")).unwrap();
}

pub(crate) fn add_member_to_existing_family(dir: &Path) {
    let d = dir.join("d");
    fs::create_dir_all(&d).unwrap();
    fs::write(
        d.join("f.py"),
        "def f(items):\n    sum = 0\n    for z in items:\n        if z > 0:\n            sum = sum + z * z\n    return sum\n",
    )
    .unwrap();
}

pub(crate) fn scan_json(out: &str) -> serde_json::Value {
    serde_json::from_str(out).expect("scan should emit valid JSON")
}

pub(crate) fn scan_families(json: &serde_json::Value) -> &[serde_json::Value] {
    json["families"]
        .as_array()
        .expect("scan JSON should contain families array")
}

pub(crate) fn family_contains_all(json: &serde_json::Value, suffixes: &[&str]) -> bool {
    family_with_all(json, suffixes).is_some()
}

pub(crate) fn family_with_all<'a>(
    json: &'a serde_json::Value,
    suffixes: &[&str],
) -> Option<&'a serde_json::Value> {
    scan_families(json).iter().find(|family| {
        let Some(locations) = family["locations"].as_array() else {
            return false;
        };
        suffixes.iter().all(|suffix| {
            locations.iter().any(|loc| {
                loc["file"]
                    .as_str()
                    .is_some_and(|file| file.ends_with(suffix))
            })
        })
    })
}

pub(crate) fn json_array_strings<'a>(value: &'a serde_json::Value, key: &str) -> Vec<&'a str> {
    value[key]
        .as_array()
        .unwrap_or_else(|| panic!("{key} should be an array"))
        .iter()
        .map(|item| {
            item.as_str()
                .unwrap_or_else(|| panic!("{key} entries should be strings"))
        })
        .collect()
}

pub(crate) fn assert_scan_json_v1_contract(json: &serde_json::Value) {
    assert_eq!(json["schema_version"], 1);
    assert!(
        json["tool_version"].as_str().is_some_and(|s| !s.is_empty()),
        "tool_version should be a non-empty string: {json}"
    );
    assert!(
        json["scope"]["files"].is_number(),
        "scope.files should be numeric: {json}"
    );
    assert!(
        json["scope"]["languages"].as_array().is_some(),
        "scope.languages should be an array: {json}"
    );

    let ranking = json["ranking"].as_object().expect("ranking object");
    for key in ["sort", "total_families", "shown_families", "limit"] {
        assert!(ranking.contains_key(key), "ranking.{key} missing: {json}");
    }

    let family = scan_families(json)
        .first()
        .expect("fixture should include a family");
    let family = family.as_object().expect("family object");
    for key in [
        "family_id",
        "value",
        "members",
        "files",
        "modules",
        "languages",
        "mean_score",
        "mean_lines",
        "dup_lines",
        "shared_lines",
        "params",
        "shared_weight",
        "locations",
        "mean_sem",
        "scope",
        "discount",
        "recommended_surface",
    ] {
        assert!(family.contains_key(key), "family.{key} missing: {json}");
    }

    let loc = family["locations"]
        .as_array()
        .and_then(|locations| locations.first())
        .and_then(|location| location.as_object())
        .expect("family.locations should contain location objects");
    for key in [
        "file",
        "start_line",
        "end_line",
        "lang",
        "kind",
        "sem",
        "span_lines",
        "span_tokens",
        "is_fragment",
    ] {
        assert!(loc.contains_key(key), "location.{key} missing: {json}");
    }
}
