use super::*;

mod group_0;
mod group_1;

pub(super) static BUILTIN_PACK_DESCRIPTORS: [BuiltinPackDescriptor; 44] = [
    group_0::DESCRIPTORS[0],
    group_0::DESCRIPTORS[1],
    group_0::DESCRIPTORS[2],
    group_0::DESCRIPTORS[3],
    group_0::DESCRIPTORS[4],
    group_0::DESCRIPTORS[5],
    group_0::DESCRIPTORS[6],
    group_0::DESCRIPTORS[7],
    group_0::DESCRIPTORS[8],
    group_0::DESCRIPTORS[9],
    group_0::DESCRIPTORS[10],
    group_0::DESCRIPTORS[11],
    group_0::DESCRIPTORS[12],
    group_0::DESCRIPTORS[13],
    group_0::DESCRIPTORS[14],
    group_0::DESCRIPTORS[15],
    group_0::DESCRIPTORS[16],
    group_0::DESCRIPTORS[17],
    group_0::DESCRIPTORS[18],
    group_0::DESCRIPTORS[19],
    group_1::DESCRIPTORS[0],
    group_1::DESCRIPTORS[1],
    group_1::DESCRIPTORS[2],
    group_1::DESCRIPTORS[3],
    group_1::DESCRIPTORS[4],
    group_1::DESCRIPTORS[5],
    group_1::DESCRIPTORS[6],
    group_1::DESCRIPTORS[7],
    group_1::DESCRIPTORS[8],
    group_1::DESCRIPTORS[9],
    group_1::DESCRIPTORS[10],
    group_1::DESCRIPTORS[11],
    group_1::DESCRIPTORS[12],
    group_1::DESCRIPTORS[13],
    group_1::DESCRIPTORS[14],
    group_1::DESCRIPTORS[15],
    group_1::DESCRIPTORS[16],
    group_1::DESCRIPTORS[17],
    group_1::DESCRIPTORS[18],
    group_1::DESCRIPTORS[19],
    group_1::DESCRIPTORS[20],
    group_1::DESCRIPTORS[21],
    group_1::DESCRIPTORS[22],
    group_1::DESCRIPTORS[23],
];
