use super::*;

#[test]
fn promise_then_receiver_obligation_is_primary_for_selector_only_then() {
    let labels = [
        "lowered-runtime-boundary-contract",
        "promise-then-promise-like-receiver-proof",
        "promise-then-fulfillment-continuation-contract",
        "promise-then-rejection-continuation-contract",
        "promise-then-callback-demand-effect-contract",
    ];

    assert_eq!(
        runtime_boundary_obligation(&labels),
        (
            "ambiguous-selector-boundary",
            "promise-then-promise-like-receiver-proof-missing",
        )
    );
}

#[test]
fn promise_receiver_producer_obligations_are_primary_when_present() {
    assert_eq!(
        runtime_boundary_obligation(&[
            "promise-executor-callback-effect-contract",
            "promise-constructor-receiver-producer-proof",
            "promise-then-promise-like-receiver-proof",
        ]),
        (
            "success-error-result-channel",
            "promise-constructor-receiver-producer-proof-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&[
            "async-function-scheduling-contract",
            "promise-async-function-return-producer-proof",
            "promise-then-promise-like-receiver-proof",
        ]),
        (
            "scheduling-boundary",
            "promise-async-function-return-producer-proof-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&[
            "promise-call-return-receiver-producer-proof",
            "promise-call-return-member-callee-proof",
            "promise-then-promise-like-receiver-proof",
        ]),
        (
            "ambiguous-selector-boundary",
            "promise-call-return-member-callee-proof-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&[
            "promise-call-return-receiver-producer-proof",
            "promise-call-return-imported-member-settled-value-contract",
            "promise-then-promise-like-receiver-proof",
        ]),
        (
            "success-error-result-channel",
            "promise-call-return-imported-member-settled-value-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&[
            "promise-call-return-receiver-producer-proof",
            "promise-then-promise-like-receiver-proof",
        ]),
        (
            "ambiguous-selector-boundary",
            "promise-call-return-receiver-producer-proof-missing",
        )
    );
}

#[test]
fn promise_then_continuation_and_callback_labels_have_standalone_obligations() {
    assert_eq!(
        runtime_boundary_obligation(&["promise-then-fulfillment-continuation-contract"]),
        (
            "success-error-result-channel",
            "promise-then-fulfillment-continuation-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&["promise-then-rejection-continuation-contract"]),
        (
            "rejection-channel",
            "promise-then-rejection-continuation-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&["promise-then-callback-demand-effect-contract"]),
        (
            "callback-demand-effect",
            "promise-then-callback-demand-effect-contract-missing",
        )
    );
}

#[test]
fn async_protocol_labels_have_specific_obligations() {
    assert_eq!(
        runtime_boundary_obligation(&["async-await-scheduling-contract"]),
        (
            "scheduling-boundary",
            "async-await-scheduling-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&["promise-await-scheduling-contract"]),
        (
            "scheduling-boundary",
            "promise-await-scheduling-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&["async-function-scheduling-contract"]),
        (
            "scheduling-boundary",
            "async-function-scheduling-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&["async-block-scheduling-contract"]),
        (
            "scheduling-boundary",
            "async-block-scheduling-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&["promise-async-function-scheduling-contract"]),
        (
            "scheduling-boundary",
            "promise-async-function-scheduling-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&["future-async-block-scheduling-contract"]),
        (
            "scheduling-boundary",
            "future-async-block-scheduling-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&[
            "async-iteration-lifecycle-contract",
            "async-iteration-value-channel-contract",
            "async-await-scheduling-contract",
        ]),
        (
            "lifecycle-materialization-boundary",
            "async-iteration-lifecycle-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&["async-iteration-value-channel-contract"]),
        (
            "success-error-result-channel",
            "async-iteration-value-channel-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&[
            "async-context-lifecycle-contract",
            "async-context-cleanup-contract",
            "exception-channel-contract",
            "async-await-scheduling-contract",
        ]),
        (
            "lifecycle-materialization-boundary",
            "async-context-lifecycle-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&["async-context-cleanup-contract"]),
        (
            "lifecycle-materialization-boundary",
            "async-context-cleanup-contract-missing",
        )
    );
}

#[test]
fn aggregate_executor_scheduler_and_lifecycle_labels_have_specific_obligations() {
    assert_eq!(
        runtime_boundary_obligation(&[
            "promise-executor-timing-contract",
            "promise-executor-callback-effect-contract",
        ]),
        (
            "executor-callback",
            "promise-executor-timing-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&[
            "promise-aggregate-first-settled-contract",
            "promise-aggregate-result-channel-contract",
        ]),
        (
            "cancellation-liveness-boundary",
            "promise-aggregate-first-settled-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&[
            "promise-aggregate-all-settled-contract",
            "promise-aggregate-result-channel-contract",
        ]),
        (
            "success-error-result-channel",
            "promise-aggregate-all-settled-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&["scheduler-yield-microtask-order-contract"]),
        (
            "scheduling-boundary",
            "scheduler-yield-microtask-order-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&["scheduler-wait-cancellation-liveness-contract"]),
        (
            "cancellation-liveness-boundary",
            "scheduler-wait-cancellation-liveness-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&["timer-scheduling-contract"]),
        ("scheduling-boundary", "timer-scheduling-contract-missing",)
    );
    assert_eq!(
        runtime_boundary_obligation(&["timer-cancellation-liveness-contract"]),
        (
            "cancellation-liveness-boundary",
            "timer-cancellation-liveness-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&["interval-async-iteration-lifecycle-contract"]),
        (
            "lifecycle-materialization-boundary",
            "interval-async-iteration-lifecycle-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&["interval-cancellation-liveness-contract"]),
        (
            "cancellation-liveness-boundary",
            "interval-cancellation-liveness-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&[
            "abort-signal-cancellation-contract",
            "abort-signal-lifecycle-contract",
        ]),
        (
            "cancellation-liveness-boundary",
            "abort-signal-cancellation-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&["abort-controller-signal-lifecycle-contract"]),
        (
            "cancellation-liveness-boundary",
            "abort-controller-signal-lifecycle-contract-missing",
        )
    );
}

#[test]
fn task_and_async_aggregate_labels_have_specific_obligations() {
    assert_eq!(
        runtime_boundary_obligation(&[
            "task-spawn-scheduling-contract",
            "task-handle-lifecycle-contract",
            "task-cancellation-liveness-contract",
        ]),
        (
            "scheduling-boundary",
            "task-spawn-scheduling-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&["task-handle-lifecycle-contract"]),
        (
            "lifecycle-materialization-boundary",
            "task-handle-lifecycle-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&["task-yield-scheduling-contract"]),
        (
            "scheduling-boundary",
            "task-yield-scheduling-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&["task-cancellation-liveness-contract"]),
        (
            "cancellation-liveness-boundary",
            "task-cancellation-liveness-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&[
            "async-aggregate-all-completion-contract",
            "async-aggregate-result-channel-contract",
        ]),
        (
            "success-error-result-channel",
            "async-aggregate-all-completion-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&[
            "async-aggregate-first-completion-contract",
            "async-aggregate-cancellation-liveness-contract",
            "async-aggregate-result-channel-contract",
        ]),
        (
            "cancellation-liveness-boundary",
            "async-aggregate-first-completion-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&[
            "async-aggregate-completion-contract",
            "async-aggregate-cancellation-liveness-contract",
            "async-aggregate-result-channel-contract",
        ]),
        (
            "success-error-result-channel",
            "async-aggregate-completion-contract-missing",
        )
    );
}

#[test]
fn future_channel_and_continuation_labels_have_specific_obligations() {
    assert_eq!(
        runtime_boundary_obligation(&[
            "future-drive-scheduling-contract",
            "future-settled-value-channel-contract",
        ]),
        (
            "scheduling-boundary",
            "future-drive-scheduling-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&["future-settled-value-channel-contract"]),
        (
            "success-error-result-channel",
            "future-settled-value-channel-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&["future-fulfillment-continuation-contract"]),
        (
            "success-error-result-channel",
            "future-fulfillment-continuation-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&["future-settlement-continuation-contract"]),
        (
            "success-error-result-channel",
            "future-settlement-continuation-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&["future-exception-continuation-contract"]),
        (
            "exception-channel",
            "future-exception-continuation-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&["future-callback-demand-effect-contract"]),
        (
            "callback-demand-effect",
            "future-callback-demand-effect-contract-missing",
        )
    );
}

#[test]
fn channel_send_receive_labels_have_specific_obligations() {
    assert_eq!(
        runtime_boundary_obligation(&[
            "channel-send-synchronization-contract",
            "channel-send-receive-protocol-contract",
        ]),
        (
            "channel-boundary",
            "channel-send-synchronization-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&[
            "channel-receive-status-contract",
            "channel-receive-value-channel-contract",
        ]),
        (
            "channel-boundary",
            "channel-receive-status-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&["channel-receive-value-channel-contract"]),
        (
            "channel-boundary",
            "channel-receive-value-channel-contract-missing",
        )
    );
}

#[test]
fn channel_select_labels_are_primary_over_nested_operations() {
    assert_eq!(
        runtime_boundary_obligation(&["channel-select-readiness-contract"]),
        (
            "channel-boundary",
            "channel-select-readiness-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&["channel-select-case-selection-contract"]),
        (
            "channel-boundary",
            "channel-select-case-selection-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&["channel-select-default-liveness-contract"]),
        (
            "channel-boundary",
            "channel-select-default-liveness-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&[
            "channel-select-readiness-contract",
            "channel-select-case-selection-contract",
            "channel-receive-value-channel-contract",
            "channel-select-protocol-contract",
        ]),
        (
            "channel-boundary",
            "channel-select-readiness-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&[
            "channel-select-case-selection-contract",
            "channel-send-synchronization-contract",
            "channel-select-protocol-contract",
        ]),
        (
            "channel-boundary",
            "channel-select-case-selection-contract-missing",
        )
    );
}

#[test]
fn goroutine_and_defer_labels_have_specific_obligations() {
    assert_eq!(
        runtime_boundary_obligation(&[
            "defer-lifecycle-ordering-contract",
            "defer-callback-effect-contract",
        ]),
        (
            "lifecycle-materialization-boundary",
            "defer-lifecycle-ordering-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&["defer-callback-effect-contract"]),
        (
            "callback-demand-effect",
            "defer-callback-effect-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&[
            "goroutine-scheduling-contract",
            "goroutine-callback-effect-contract",
        ]),
        (
            "scheduling-boundary",
            "goroutine-scheduling-contract-missing",
        )
    );
    assert_eq!(
        runtime_boundary_obligation(&["goroutine-callback-effect-contract"]),
        (
            "callback-demand-effect",
            "goroutine-callback-effect-contract-missing",
        )
    );
}
