use super::*;

pub(super) const DESCRIPTORS: [BuiltinPackDescriptor; 26] = [
    BuiltinPackDescriptor {
        id: JAVA_STDLIB_MATH_PACK_ID,
        kind: SemanticPackKind::StdlibPack,
        display_name: "nose Java stdlib Math pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: JAVA_LANGUAGE,
        supported_packages: JAVA_STDLIB_MATH_PACKAGES,
        language: None,
        evidence_producer_ids: JAVA_STDLIB_MATH_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: JAVA_STDLIB_MATH_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: JAVA_STDLIB_MATH_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: java_stdlib_math_counts,
    },
    BuiltinPackDescriptor {
        id: JAVA_STDLIB_MAP_FACTORY_PACK_ID,
        kind: SemanticPackKind::StdlibPack,
        display_name: "nose Java stdlib map factory pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: JAVA_LANGUAGE,
        supported_packages: JAVA_STDLIB_MAP_FACTORY_PACKAGES,
        language: None,
        evidence_producer_ids: JAVA_STDLIB_MAP_FACTORY_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: JAVA_STDLIB_MAP_FACTORY_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: JAVA_STDLIB_MAP_FACTORY_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: java_stdlib_map_factory_counts,
    },
    BuiltinPackDescriptor {
        id: JAVA_STDLIB_MAP_ENTRY_PACK_ID,
        kind: SemanticPackKind::StdlibPack,
        display_name: "nose Java stdlib map entry pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: JAVA_LANGUAGE,
        supported_packages: JAVA_STDLIB_MAP_ENTRY_PACKAGES,
        language: None,
        evidence_producer_ids: JAVA_STDLIB_MAP_ENTRY_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: JAVA_STDLIB_MAP_ENTRY_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: JAVA_STDLIB_MAP_ENTRY_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: java_stdlib_map_entry_counts,
    },
    BuiltinPackDescriptor {
        id: JAVA_STDLIB_COLLECTION_FACTORY_PACK_ID,
        kind: SemanticPackKind::StdlibPack,
        display_name: "nose Java stdlib collection factory pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: JAVA_LANGUAGE,
        supported_packages: JAVA_STDLIB_COLLECTION_FACTORY_PACKAGES,
        language: None,
        evidence_producer_ids: JAVA_STDLIB_COLLECTION_FACTORY_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: JAVA_STDLIB_COLLECTION_FACTORY_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: JAVA_STDLIB_COLLECTION_FACTORY_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: java_stdlib_collection_factory_counts,
    },
    BuiltinPackDescriptor {
        id: JAVA_GUAVA_IMMUTABLE_COLLECTION_FACTORY_PACK_ID,
        kind: SemanticPackKind::LibraryPack,
        display_name: "nose Java Guava immutable collection factory pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: JAVA_LANGUAGE,
        supported_packages: JAVA_GUAVA_IMMUTABLE_COLLECTION_FACTORY_PACKAGES,
        language: None,
        evidence_producer_ids: JAVA_GUAVA_IMMUTABLE_COLLECTION_FACTORY_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: JAVA_GUAVA_IMMUTABLE_COLLECTION_FACTORY_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: JAVA_GUAVA_IMMUTABLE_COLLECTION_FACTORY_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: java_guava_immutable_collection_factory_counts,
    },
    BuiltinPackDescriptor {
        id: JAVA_STDLIB_COLLECTION_CONSTRUCTOR_PACK_ID,
        kind: SemanticPackKind::StdlibPack,
        display_name: "nose Java stdlib collection constructor pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: JAVA_LANGUAGE,
        supported_packages: JAVA_STDLIB_COLLECTION_CONSTRUCTOR_PACKAGES,
        language: None,
        evidence_producer_ids: JAVA_STDLIB_COLLECTION_CONSTRUCTOR_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: JAVA_STDLIB_COLLECTION_CONSTRUCTOR_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: JAVA_STDLIB_COLLECTION_CONSTRUCTOR_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: java_stdlib_collection_constructor_counts,
    },
    BuiltinPackDescriptor {
        id: JAVA_STDLIB_STATIC_COLLECTION_ADAPTER_PACK_ID,
        kind: SemanticPackKind::StdlibPack,
        display_name: "nose Java stdlib static collection adapter pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: JAVA_LANGUAGE,
        supported_packages: JAVA_STDLIB_STATIC_COLLECTION_ADAPTER_PACKAGES,
        language: None,
        evidence_producer_ids: JAVA_STDLIB_STATIC_COLLECTION_ADAPTER_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: JAVA_STDLIB_STATIC_COLLECTION_ADAPTER_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: JAVA_STDLIB_STATIC_COLLECTION_ADAPTER_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: java_stdlib_static_collection_adapter_counts,
    },
    BuiltinPackDescriptor {
        id: MAP_GET_PROTOCOL_PACK_ID,
        kind: SemanticPackKind::ProtocolPack,
        display_name: "nose map-get protocol pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: MAP_GET_PROTOCOL_LANGUAGES,
        supported_packages: MAP_GET_PROTOCOL_PACKAGES,
        language: None,
        evidence_producer_ids: MAP_GET_PROTOCOL_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: MAP_GET_PROTOCOL_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: MAP_GET_PROTOCOL_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: map_get_protocol_counts,
    },
    BuiltinPackDescriptor {
        id: MAP_GET_DEFAULT_PROTOCOL_PACK_ID,
        kind: SemanticPackKind::ProtocolPack,
        display_name: "nose map-get-default protocol pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: MAP_GET_DEFAULT_PROTOCOL_LANGUAGES,
        supported_packages: MAP_GET_DEFAULT_PROTOCOL_PACKAGES,
        language: None,
        evidence_producer_ids: MAP_GET_DEFAULT_PROTOCOL_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: MAP_GET_DEFAULT_PROTOCOL_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: MAP_GET_DEFAULT_PROTOCOL_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: map_get_default_protocol_counts,
    },
    BuiltinPackDescriptor {
        id: FREE_FUNCTION_BUILTIN_PROTOCOL_PACK_ID,
        kind: SemanticPackKind::ProtocolPack,
        display_name: "nose free-function builtin protocol pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: FREE_FUNCTION_BUILTIN_PROTOCOL_LANGUAGES,
        supported_packages: FREE_FUNCTION_BUILTIN_PROTOCOL_PACKAGES,
        language: None,
        evidence_producer_ids: FREE_FUNCTION_BUILTIN_PROTOCOL_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: FREE_FUNCTION_BUILTIN_PROTOCOL_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: FREE_FUNCTION_BUILTIN_PROTOCOL_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: free_function_builtin_protocol_counts,
    },
    BuiltinPackDescriptor {
        id: PYTHON_ITERATOR_BUILTIN_PROTOCOL_PACK_ID,
        kind: SemanticPackKind::ProtocolPack,
        display_name: "nose Python iterator builtin protocol pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: PYTHON_ITERATOR_BUILTIN_PROTOCOL_LANGUAGES,
        supported_packages: PYTHON_ITERATOR_BUILTIN_PROTOCOL_PACKAGES,
        language: None,
        evidence_producer_ids: PYTHON_ITERATOR_BUILTIN_PROTOCOL_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: PYTHON_ITERATOR_BUILTIN_PROTOCOL_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: PYTHON_ITERATOR_BUILTIN_PROTOCOL_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: python_iterator_builtin_protocol_counts,
    },
    BuiltinPackDescriptor {
        id: RECEIVER_MEMBERSHIP_PROTOCOL_PACK_ID,
        kind: SemanticPackKind::ProtocolPack,
        display_name: "nose receiver-membership protocol pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: RECEIVER_MEMBERSHIP_PROTOCOL_LANGUAGES,
        supported_packages: RECEIVER_MEMBERSHIP_PROTOCOL_PACKAGES,
        language: None,
        evidence_producer_ids: RECEIVER_MEMBERSHIP_PROTOCOL_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: RECEIVER_MEMBERSHIP_PROTOCOL_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: RECEIVER_MEMBERSHIP_PROTOCOL_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: receiver_membership_protocol_counts,
    },
    BuiltinPackDescriptor {
        id: MAP_KEY_VIEW_PROTOCOL_PACK_ID,
        kind: SemanticPackKind::ProtocolPack,
        display_name: "nose map-key-view protocol pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: MAP_KEY_VIEW_PROTOCOL_LANGUAGES,
        supported_packages: MAP_KEY_VIEW_PROTOCOL_PACKAGES,
        language: None,
        evidence_producer_ids: MAP_KEY_VIEW_PROTOCOL_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: MAP_KEY_VIEW_PROTOCOL_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: MAP_KEY_VIEW_PROTOCOL_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: map_key_view_protocol_counts,
    },
    BuiltinPackDescriptor {
        id: PROPERTY_BUILTIN_PROTOCOL_PACK_ID,
        kind: SemanticPackKind::ProtocolPack,
        display_name: "nose property builtin protocol pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: PROPERTY_BUILTIN_PROTOCOL_LANGUAGES,
        supported_packages: PROPERTY_BUILTIN_PROTOCOL_PACKAGES,
        language: None,
        evidence_producer_ids: PROPERTY_BUILTIN_PROTOCOL_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: PROPERTY_BUILTIN_PROTOCOL_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: PROPERTY_BUILTIN_PROTOCOL_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: property_builtin_protocol_counts,
    },
    BuiltinPackDescriptor {
        id: BUILTIN_METHOD_CALL_PROTOCOL_PACK_ID,
        kind: SemanticPackKind::ProtocolPack,
        display_name: "nose builtin method-call protocol pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: BUILTIN_METHOD_CALL_PROTOCOL_LANGUAGES,
        supported_packages: BUILTIN_METHOD_CALL_PROTOCOL_PACKAGES,
        language: None,
        evidence_producer_ids: BUILTIN_METHOD_CALL_PROTOCOL_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: BUILTIN_METHOD_CALL_PROTOCOL_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: BUILTIN_METHOD_CALL_PROTOCOL_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: builtin_method_call_protocol_counts,
    },
    BuiltinPackDescriptor {
        id: SEQUENCE_HOF_ADAPTER_PROTOCOL_PACK_ID,
        kind: SemanticPackKind::ProtocolPack,
        display_name: "nose sequence HOF adapter protocol pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: SEQUENCE_HOF_ADAPTER_PROTOCOL_LANGUAGES,
        supported_packages: SEQUENCE_HOF_ADAPTER_PROTOCOL_PACKAGES,
        language: None,
        evidence_producer_ids: SEQUENCE_HOF_ADAPTER_PROTOCOL_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: SEQUENCE_HOF_ADAPTER_PROTOCOL_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: SEQUENCE_HOF_ADAPTER_PROTOCOL_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: sequence_hof_adapter_protocol_counts,
    },
    BuiltinPackDescriptor {
        id: GO_STDLIB_NAMESPACE_CALL_PACK_ID,
        kind: SemanticPackKind::StdlibPack,
        display_name: "nose Go stdlib namespace-call pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: GO_STDLIB_NAMESPACE_CALL_LANGUAGE,
        supported_packages: GO_STDLIB_NAMESPACE_CALL_PACKAGES,
        language: None,
        evidence_producer_ids: GO_STDLIB_NAMESPACE_CALL_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: GO_STDLIB_NAMESPACE_CALL_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: GO_STDLIB_NAMESPACE_CALL_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: go_stdlib_namespace_call_counts,
    },
    BuiltinPackDescriptor {
        id: ITERATOR_IDENTITY_ADAPTER_PACK_ID,
        kind: SemanticPackKind::ProtocolPack,
        display_name: "nose iterator identity adapter protocol pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: JAVA_RUST_LANGUAGE,
        supported_packages: ITERATOR_IDENTITY_ADAPTER_PACKAGES,
        language: None,
        evidence_producer_ids: ITERATOR_IDENTITY_ADAPTER_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: ITERATOR_IDENTITY_ADAPTER_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: ITERATOR_IDENTITY_ADAPTER_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: iterator_identity_adapter_counts,
    },
    BuiltinPackDescriptor {
        id: JS_LIKE_BUILTIN_PROMISE_PACK_ID,
        kind: SemanticPackKind::StdlibPack,
        display_name: "nose JavaScript builtins Promise pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: JS_LIKE_LANGUAGE,
        supported_packages: JS_LIKE_BUILTIN_PROMISE_PACKAGES,
        language: None,
        evidence_producer_ids: JS_LIKE_BUILTIN_PROMISE_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: JS_LIKE_BUILTIN_PROMISE_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: JS_LIKE_BUILTIN_PROMISE_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: js_like_builtin_promise_counts,
    },
    BuiltinPackDescriptor {
        id: JS_LIKE_BUILTIN_ARRAY_PACK_ID,
        kind: SemanticPackKind::StdlibPack,
        display_name: "nose JavaScript builtins Array pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: JS_LIKE_LANGUAGE,
        supported_packages: JS_LIKE_BUILTIN_ARRAY_PACKAGES,
        language: None,
        evidence_producer_ids: JS_LIKE_BUILTIN_ARRAY_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: JS_LIKE_BUILTIN_ARRAY_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: JS_LIKE_BUILTIN_ARRAY_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: js_like_builtin_array_counts,
    },
    BuiltinPackDescriptor {
        id: JS_LIKE_BUILTIN_BOOLEAN_PACK_ID,
        kind: SemanticPackKind::StdlibPack,
        display_name: "nose JavaScript builtins Boolean pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: JS_LIKE_LANGUAGE,
        supported_packages: JS_LIKE_BUILTIN_BOOLEAN_PACKAGES,
        language: None,
        evidence_producer_ids: JS_LIKE_BUILTIN_BOOLEAN_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: JS_LIKE_BUILTIN_BOOLEAN_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: JS_LIKE_BUILTIN_BOOLEAN_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: js_like_builtin_boolean_counts,
    },
    BuiltinPackDescriptor {
        id: JS_LIKE_BUILTIN_REGEX_PACK_ID,
        kind: SemanticPackKind::StdlibPack,
        display_name: "nose JavaScript builtins RegExp pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: JS_LIKE_LANGUAGE,
        supported_packages: JS_LIKE_BUILTIN_REGEX_PACKAGES,
        language: None,
        evidence_producer_ids: JS_LIKE_BUILTIN_REGEX_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: JS_LIKE_BUILTIN_REGEX_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: JS_LIKE_BUILTIN_REGEX_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: js_like_builtin_regex_counts,
    },
    BuiltinPackDescriptor {
        id: JS_LIKE_BUILTIN_STATIC_INDEX_MEMBERSHIP_PACK_ID,
        kind: SemanticPackKind::StdlibPack,
        display_name: "nose JavaScript builtins static index membership pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: JS_LIKE_LANGUAGE,
        supported_packages: JS_LIKE_BUILTIN_STATIC_INDEX_MEMBERSHIP_PACKAGES,
        language: None,
        evidence_producer_ids: JS_LIKE_BUILTIN_STATIC_INDEX_MEMBERSHIP_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: JS_LIKE_BUILTIN_STATIC_INDEX_MEMBERSHIP_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: JS_LIKE_BUILTIN_STATIC_INDEX_MEMBERSHIP_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: js_like_builtin_static_index_membership_counts,
    },
    BuiltinPackDescriptor {
        id: JS_LIKE_BUILTIN_COLLECTION_CONSTRUCTOR_PACK_ID,
        kind: SemanticPackKind::StdlibPack,
        display_name: "nose JavaScript builtins collection constructor pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: JS_LIKE_LANGUAGE,
        supported_packages: JS_LIKE_BUILTIN_COLLECTION_CONSTRUCTOR_PACKAGES,
        language: None,
        evidence_producer_ids: JS_LIKE_BUILTIN_COLLECTION_CONSTRUCTOR_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: JS_LIKE_BUILTIN_COLLECTION_CONSTRUCTOR_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: JS_LIKE_BUILTIN_COLLECTION_CONSTRUCTOR_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: js_like_builtin_collection_constructor_counts,
    },
    BuiltinPackDescriptor {
        id: PYTHON_STDLIB_TYPE_DOMAIN_PACK_ID,
        kind: SemanticPackKind::StdlibPack,
        display_name: "nose Python stdlib type-domain pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: PYTHON_LANGUAGE,
        supported_packages: PYTHON_STDLIB_TYPE_DOMAIN_PACKAGES,
        language: None,
        evidence_producer_ids: PYTHON_STDLIB_TYPE_DOMAIN_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: PYTHON_STDLIB_TYPE_DOMAIN_CONTRACT_IDS,
        type_domain_alias_contracts: PYTHON_STDLIB_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: NO_IDS,
        dynamic_conformance_refs: Some(python_stdlib_type_domain_conformance_refs),
        counts: python_stdlib_type_domain_counts,
    },
    BuiltinPackDescriptor {
        id: VALUE_GRAPH_LAW_PACK_ID,
        kind: SemanticPackKind::LawPack,
        display_name: "nose value-graph law pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: NO_LANGUAGES,
        supported_packages: NO_PACKAGES,
        language: None,
        evidence_producer_ids: NO_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: NO_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: Some(value_graph_law_ids),
        static_conformance_refs: NO_IDS,
        dynamic_conformance_refs: Some(value_graph_law_conformance_refs),
        counts: value_graph_law_counts,
    },
];
