use super::*;

pub(super) const DESCRIPTORS: [BuiltinPackDescriptor; 23] = [
    BuiltinPackDescriptor {
        id: BUILTIN_COMPAT_PACK_ID,
        kind: SemanticPackKind::LanguagePack,
        display_name: "nose builtin semantic compatibility facade",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: NO_LANGUAGES,
        supported_packages: NO_PACKAGES,
        language: None,
        evidence_producer_ids: NO_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: NO_IDS,
        static_value_law_ids: NO_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        dynamic_value_law_ids: None,
        static_conformance_refs: NO_IDS,
        dynamic_conformance_refs: None,
        counts: empty_counts,
    },
    BuiltinPackDescriptor {
        id: PYTHON_LANGUAGE_PACK_ID,
        kind: SemanticPackKind::LanguagePack,
        display_name: "nose Python language pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: PYTHON_LANGUAGE,
        supported_packages: NO_PACKAGES,
        language: Some(BuiltinLanguageBinding {
            langs: PYTHON_BINDING_LANGS,
            file_extensions: PYTHON_LANGUAGE_FILE_EXTENSIONS,
            parser: "tree-sitter-python",
            lowering_entrypoint: "nose_frontend::python::lower",
        }),
        evidence_producer_ids: PYTHON_LANGUAGE_PRODUCER_IDS,
        source_fact_producer_ids: PYTHON_LANGUAGE_SOURCE_FACT_PRODUCER_IDS,
        contract_ids: NO_IDS,
        static_value_law_ids: NO_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        dynamic_value_law_ids: None,
        static_conformance_refs: NO_IDS,
        dynamic_conformance_refs: None,
        counts: language_core_and_source_fact_counts,
    },
    BuiltinPackDescriptor {
        id: JS_TS_LANGUAGE_PACK_ID,
        kind: SemanticPackKind::LanguagePack,
        display_name: "nose JavaScript/TypeScript language pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: JS_LIKE_LANGUAGE,
        supported_packages: NO_PACKAGES,
        language: Some(BuiltinLanguageBinding {
            langs: JS_TS_BINDING_LANGS,
            file_extensions: JS_TS_LANGUAGE_FILE_EXTENSIONS,
            parser: "tree-sitter-javascript/tree-sitter-typescript",
            lowering_entrypoint: "nose_frontend::js_ts::lower",
        }),
        evidence_producer_ids: JS_TS_LANGUAGE_PRODUCER_IDS,
        source_fact_producer_ids: JS_TS_LANGUAGE_SOURCE_FACT_PRODUCER_IDS,
        contract_ids: NO_IDS,
        static_value_law_ids: NO_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        dynamic_value_law_ids: None,
        static_conformance_refs: NO_IDS,
        dynamic_conformance_refs: None,
        counts: language_core_and_source_fact_counts,
    },
    BuiltinPackDescriptor {
        id: GO_LANGUAGE_PACK_ID,
        kind: SemanticPackKind::LanguagePack,
        display_name: "nose Go language pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: GO_LANGUAGE,
        supported_packages: NO_PACKAGES,
        language: Some(BuiltinLanguageBinding {
            langs: GO_BINDING_LANGS,
            file_extensions: GO_LANGUAGE_FILE_EXTENSIONS,
            parser: "tree-sitter-go",
            lowering_entrypoint: "nose_frontend::go::lower",
        }),
        evidence_producer_ids: GO_LANGUAGE_PRODUCER_IDS,
        source_fact_producer_ids: GO_LANGUAGE_SOURCE_FACT_PRODUCER_IDS,
        contract_ids: NO_IDS,
        static_value_law_ids: NO_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        dynamic_value_law_ids: None,
        static_conformance_refs: NO_IDS,
        dynamic_conformance_refs: None,
        counts: language_core_and_source_fact_counts,
    },
    BuiltinPackDescriptor {
        id: RUST_LANGUAGE_PACK_ID,
        kind: SemanticPackKind::LanguagePack,
        display_name: "nose Rust language pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: RUST_LANGUAGE,
        supported_packages: NO_PACKAGES,
        language: Some(BuiltinLanguageBinding {
            langs: RUST_BINDING_LANGS,
            file_extensions: RUST_LANGUAGE_FILE_EXTENSIONS,
            parser: "tree-sitter-rust",
            lowering_entrypoint: "nose_frontend::rust::lower",
        }),
        evidence_producer_ids: RUST_LANGUAGE_PRODUCER_IDS,
        source_fact_producer_ids: RUST_LANGUAGE_SOURCE_FACT_PRODUCER_IDS,
        contract_ids: NO_IDS,
        static_value_law_ids: NO_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        dynamic_value_law_ids: None,
        static_conformance_refs: NO_IDS,
        dynamic_conformance_refs: None,
        counts: language_core_and_source_fact_counts,
    },
    BuiltinPackDescriptor {
        id: JAVA_LANGUAGE_PACK_ID,
        kind: SemanticPackKind::LanguagePack,
        display_name: "nose Java language pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: JAVA_LANGUAGE,
        supported_packages: NO_PACKAGES,
        language: Some(BuiltinLanguageBinding {
            langs: JAVA_BINDING_LANGS,
            file_extensions: JAVA_LANGUAGE_FILE_EXTENSIONS,
            parser: "tree-sitter-java",
            lowering_entrypoint: "nose_frontend::java::lower",
        }),
        evidence_producer_ids: JAVA_LANGUAGE_PRODUCER_IDS,
        source_fact_producer_ids: JAVA_LANGUAGE_SOURCE_FACT_PRODUCER_IDS,
        contract_ids: NO_IDS,
        static_value_law_ids: NO_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        dynamic_value_law_ids: None,
        static_conformance_refs: NO_IDS,
        dynamic_conformance_refs: None,
        counts: language_core_and_source_fact_counts,
    },
    BuiltinPackDescriptor {
        id: C_LANGUAGE_PACK_ID,
        kind: SemanticPackKind::LanguagePack,
        display_name: "nose C language pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: C_LANGUAGE,
        supported_packages: NO_PACKAGES,
        language: Some(BuiltinLanguageBinding {
            langs: C_BINDING_LANGS,
            file_extensions: C_LANGUAGE_FILE_EXTENSIONS,
            parser: "tree-sitter-c",
            lowering_entrypoint: "nose_frontend::c::lower",
        }),
        evidence_producer_ids: C_LANGUAGE_PRODUCER_IDS,
        source_fact_producer_ids: C_LANGUAGE_SOURCE_FACT_PRODUCER_IDS,
        contract_ids: NO_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: C_LANGUAGE_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: c_language_counts,
    },
    BuiltinPackDescriptor {
        id: RUBY_LANGUAGE_PACK_ID,
        kind: SemanticPackKind::LanguagePack,
        display_name: "nose Ruby language pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: RUBY_LANGUAGE,
        supported_packages: NO_PACKAGES,
        language: Some(BuiltinLanguageBinding {
            langs: RUBY_BINDING_LANGS,
            file_extensions: RUBY_LANGUAGE_FILE_EXTENSIONS,
            parser: "tree-sitter-ruby",
            lowering_entrypoint: "nose_frontend::ruby::lower",
        }),
        evidence_producer_ids: RUBY_LANGUAGE_PRODUCER_IDS,
        source_fact_producer_ids: RUBY_LANGUAGE_SOURCE_FACT_PRODUCER_IDS,
        contract_ids: NO_IDS,
        static_value_law_ids: NO_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        dynamic_value_law_ids: None,
        static_conformance_refs: NO_IDS,
        dynamic_conformance_refs: None,
        counts: language_core_and_source_fact_counts,
    },
    BuiltinPackDescriptor {
        id: SWIFT_LANGUAGE_PACK_ID,
        kind: SemanticPackKind::LanguagePack,
        display_name: "nose Swift language pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: SWIFT_LANGUAGE,
        supported_packages: NO_PACKAGES,
        language: Some(BuiltinLanguageBinding {
            langs: SWIFT_BINDING_LANGS,
            file_extensions: SWIFT_LANGUAGE_FILE_EXTENSIONS,
            parser: "tree-sitter-swift",
            lowering_entrypoint: "nose_frontend::swift::lower",
        }),
        evidence_producer_ids: SWIFT_LANGUAGE_PRODUCER_IDS,
        source_fact_producer_ids: SWIFT_LANGUAGE_SOURCE_FACT_PRODUCER_IDS,
        contract_ids: NO_IDS,
        static_value_law_ids: NO_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        dynamic_value_law_ids: None,
        static_conformance_refs: NO_IDS,
        dynamic_conformance_refs: None,
        counts: language_core_and_source_fact_counts,
    },
    BuiltinPackDescriptor {
        id: CSHARP_LANGUAGE_PACK_ID,
        kind: SemanticPackKind::LanguagePack,
        display_name: "nose C# language pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: CSHARP_LANGUAGE,
        supported_packages: NO_PACKAGES,
        language: Some(BuiltinLanguageBinding {
            langs: CSHARP_BINDING_LANGS,
            file_extensions: CSHARP_LANGUAGE_FILE_EXTENSIONS,
            parser: "tree-sitter-c-sharp",
            lowering_entrypoint: "nose_frontend::csharp::lower",
        }),
        evidence_producer_ids: CSHARP_LANGUAGE_PRODUCER_IDS,
        source_fact_producer_ids: CSHARP_LANGUAGE_SOURCE_FACT_PRODUCER_IDS,
        contract_ids: NO_IDS,
        static_value_law_ids: NO_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        dynamic_value_law_ids: None,
        static_conformance_refs: NO_IDS,
        dynamic_conformance_refs: None,
        counts: language_core_and_source_fact_counts,
    },
    BuiltinPackDescriptor {
        id: CSS_LANGUAGE_PACK_ID,
        kind: SemanticPackKind::LanguagePack,
        display_name: "nose CSS language pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: CSS_LANGUAGE,
        supported_packages: NO_PACKAGES,
        language: Some(BuiltinLanguageBinding {
            langs: CSS_BINDING_LANGS,
            file_extensions: CSS_LANGUAGE_FILE_EXTENSIONS,
            parser: "tree-sitter-css",
            lowering_entrypoint: "nose_frontend::css::lower",
        }),
        evidence_producer_ids: CSS_LANGUAGE_PRODUCER_IDS,
        source_fact_producer_ids: CSS_LANGUAGE_SOURCE_FACT_PRODUCER_IDS,
        contract_ids: NO_IDS,
        static_value_law_ids: NO_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        dynamic_value_law_ids: None,
        static_conformance_refs: NO_IDS,
        dynamic_conformance_refs: None,
        counts: language_core_and_source_fact_counts,
    },
    BuiltinPackDescriptor {
        id: HTML_EMBEDDED_LANGUAGE_PACK_ID,
        kind: SemanticPackKind::LanguagePack,
        display_name: "nose HTML/Vue/Svelte embedded region language pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: HTML_EMBEDDED_LANGUAGES,
        supported_packages: NO_PACKAGES,
        language: Some(BuiltinLanguageBinding {
            langs: HTML_EMBEDDED_BINDING_LANGS,
            file_extensions: HTML_EMBEDDED_LANGUAGE_FILE_EXTENSIONS,
            parser: "tree-sitter-html + embedded JS/TS/CSS extraction",
            lowering_entrypoint: "nose_frontend::embedded::lower_regions",
        }),
        evidence_producer_ids: HTML_EMBEDDED_LANGUAGE_PRODUCER_IDS,
        source_fact_producer_ids: HTML_EMBEDDED_LANGUAGE_SOURCE_FACT_PRODUCER_IDS,
        contract_ids: NO_IDS,
        static_value_law_ids: NO_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        dynamic_value_law_ids: None,
        static_conformance_refs: NO_IDS,
        dynamic_conformance_refs: None,
        counts: language_core_and_source_fact_counts,
    },
    BuiltinPackDescriptor {
        id: PYTHON_BUILTIN_COLLECTION_FACTORY_PACK_ID,
        kind: SemanticPackKind::StdlibPack,
        display_name: "nose Python builtins collection factory pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: PYTHON_LANGUAGE,
        supported_packages: PYTHON_BUILTIN_PACKAGES,
        language: None,
        evidence_producer_ids: PYTHON_BUILTIN_COLLECTION_FACTORY_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: PYTHON_BUILTIN_COLLECTION_FACTORY_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: PYTHON_BUILTIN_COLLECTION_FACTORY_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: python_builtin_collection_factory_counts,
    },
    BuiltinPackDescriptor {
        id: PYTHON_STDLIB_COLLECTION_FACTORY_PACK_ID,
        kind: SemanticPackKind::StdlibPack,
        display_name: "nose Python stdlib collection factory pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: PYTHON_LANGUAGE,
        supported_packages: PYTHON_STDLIB_COLLECTION_FACTORY_PACKAGES,
        language: None,
        evidence_producer_ids: PYTHON_STDLIB_COLLECTION_FACTORY_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: PYTHON_STDLIB_COLLECTION_FACTORY_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: PYTHON_STDLIB_COLLECTION_FACTORY_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: python_stdlib_collection_factory_counts,
    },
    BuiltinPackDescriptor {
        id: PYTHON_STDLIB_MATH_PACK_ID,
        kind: SemanticPackKind::StdlibPack,
        display_name: "nose Python stdlib math pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: PYTHON_LANGUAGE,
        supported_packages: PYTHON_STDLIB_MATH_PACKAGES,
        language: None,
        evidence_producer_ids: PYTHON_STDLIB_MATH_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: PYTHON_STDLIB_MATH_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: PYTHON_STDLIB_MATH_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: python_stdlib_math_counts,
    },
    BuiltinPackDescriptor {
        id: RUBY_STDLIB_SET_PACK_ID,
        kind: SemanticPackKind::StdlibPack,
        display_name: "nose Ruby stdlib Set pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: RUBY_LANGUAGE,
        supported_packages: RUBY_STDLIB_SET_PACKAGES,
        language: None,
        evidence_producer_ids: RUBY_STDLIB_SET_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: RUBY_STDLIB_SET_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: RUBY_STDLIB_SET_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: ruby_stdlib_set_counts,
    },
    BuiltinPackDescriptor {
        id: RUST_STDLIB_VEC_PACK_ID,
        kind: SemanticPackKind::StdlibPack,
        display_name: "nose Rust stdlib Vec pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: RUST_LANGUAGE,
        supported_packages: RUST_STDLIB_VEC_PACKAGES,
        language: None,
        evidence_producer_ids: RUST_STDLIB_VEC_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: RUST_STDLIB_VEC_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: RUST_STDLIB_VEC_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: rust_stdlib_vec_counts,
    },
    BuiltinPackDescriptor {
        id: RUST_STDLIB_OPTION_PACK_ID,
        kind: SemanticPackKind::StdlibPack,
        display_name: "nose Rust stdlib Option pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: RUST_LANGUAGE,
        supported_packages: RUST_STDLIB_OPTION_PACKAGES,
        language: None,
        evidence_producer_ids: RUST_STDLIB_OPTION_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: RUST_STDLIB_OPTION_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: RUST_STDLIB_OPTION_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: rust_stdlib_option_counts,
    },
    BuiltinPackDescriptor {
        id: RUST_STDLIB_RESULT_PACK_ID,
        kind: SemanticPackKind::StdlibPack,
        display_name: "nose Rust stdlib Result pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: RUST_LANGUAGE,
        supported_packages: RUST_STDLIB_RESULT_PACKAGES,
        language: None,
        evidence_producer_ids: RUST_STDLIB_RESULT_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: RUST_STDLIB_RESULT_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: RUST_STDLIB_RESULT_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: rust_stdlib_result_counts,
    },
    BuiltinPackDescriptor {
        id: RUST_STDLIB_INTEGER_METHOD_PACK_ID,
        kind: SemanticPackKind::StdlibPack,
        display_name: "nose Rust stdlib integer method pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: RUST_LANGUAGE,
        supported_packages: RUST_STDLIB_INTEGER_METHOD_PACKAGES,
        language: None,
        evidence_producer_ids: RUST_STDLIB_INTEGER_METHOD_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: RUST_STDLIB_INTEGER_METHOD_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: RUST_STDLIB_INTEGER_METHOD_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: rust_stdlib_integer_method_counts,
    },
    BuiltinPackDescriptor {
        id: RUST_STDLIB_COLLECTION_FACTORY_PACK_ID,
        kind: SemanticPackKind::StdlibPack,
        display_name: "nose Rust stdlib collection factory pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: RUST_LANGUAGE,
        supported_packages: RUST_STDLIB_COLLECTION_FACTORY_PACKAGES,
        language: None,
        evidence_producer_ids: RUST_STDLIB_COLLECTION_FACTORY_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: RUST_STDLIB_COLLECTION_FACTORY_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: RUST_STDLIB_COLLECTION_FACTORY_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: rust_stdlib_collection_factory_counts,
    },
    BuiltinPackDescriptor {
        id: RUST_STDLIB_MAP_FACTORY_PACK_ID,
        kind: SemanticPackKind::StdlibPack,
        display_name: "nose Rust stdlib map factory pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: RUST_LANGUAGE,
        supported_packages: RUST_STDLIB_MAP_FACTORY_PACKAGES,
        language: None,
        evidence_producer_ids: RUST_STDLIB_MAP_FACTORY_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: RUST_STDLIB_MAP_FACTORY_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: RUST_STDLIB_MAP_FACTORY_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: rust_stdlib_map_factory_counts,
    },
    BuiltinPackDescriptor {
        id: SWIFT_STDLIB_COLLECTION_FACTORY_PACK_ID,
        kind: SemanticPackKind::StdlibPack,
        display_name: "nose Swift stdlib collection factory pack",
        trust: PackTrust::BuiltinDefault,
        enabled_by_default: true,
        supported_languages: SWIFT_LANGUAGE,
        supported_packages: SWIFT_STDLIB_COLLECTION_FACTORY_PACKAGES,
        language: None,
        evidence_producer_ids: SWIFT_STDLIB_COLLECTION_FACTORY_PRODUCER_IDS,
        source_fact_producer_ids: NO_IDS,
        contract_ids: SWIFT_STDLIB_COLLECTION_FACTORY_CONTRACT_IDS,
        type_domain_alias_contracts: NO_TYPE_DOMAIN_ALIAS_CONTRACTS,
        static_value_law_ids: NO_IDS,
        dynamic_value_law_ids: None,
        static_conformance_refs: SWIFT_STDLIB_COLLECTION_FACTORY_CONFORMANCE_REFS,
        dynamic_conformance_refs: None,
        counts: swift_stdlib_collection_factory_counts,
    },
];
